apiVersion: apps/v1
kind: Deployment
metadata:
  name: naveen-portfolio
spec:
  replicas: 2
  selector:
    matchLabels:
      app: naveen-portfolio
  template:
    metadata:
      labels:
        app: naveen-portfolio
    spec:
      containers:
      - name: portfolio
        image: naveennavi26/naveen-portfolio:latest
        ports:
        - containerPort: 80
